[package]
name = "hello-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
postgres = "0.19.4"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"